const messages = {
    en: {
      $vuetify: {
        dataIterator: {
          rowsPerPageText: 'Results per page',
          pageText: '{0}-{1} of {2}',
          
        },
        dataTable:{
          itemsPerPageText: 'Results per page',
          sortDescending: 'sort descending',
          ariaLabel: {
            sortNone: 'sort none',
            sortDescending: 'sort descending',
          },
        },
        dataFooter: {
          prevPage: 'prov',
          nextPage: 'next',
          
          itemsPerPageAll: 'items per page all'
        },
        noDataText: "no data text",
        logout: "Logout",
        help: "Help",
        mainTitle:"Monitoring global e-commerce<br> the easy way.",
        emailAddress: "Email address",
        password: "Password",
        login: "Login ",
        rememberMe: "Remember me",
        passwordForgotten: "Password forgotten?",
        emailPwdWrong: "We're sorry. Your email or password are wrong.",
        problemLogin: "Problems logging in",
        requestSupport: "Then please send an email to hello@ecomda.de.<br>We'll get back to you as soon as possible.",
        backLogin: "Back to login",
        feedbackWelcome: "Feedback welcome!",
        askAdditional: "You'd like to have additional feature? Or something isn't working as it should? Then feel free to send us a message. We'll get in touch with you as soon as possible!",
        name: "Name",
        message: "Message",
        send: "Send",
        thanksForFeedback: "Thanks a lot for your feedback!",
        askOtherIdeas: "You have also other ideas or feature requests?",
        contactUsAnytime: "Then feel free to contact us any time:",
        thomasJohn: "Thomas John",
        headOfProduct: "Head of Product",
        phone: "Phone",
        cell: "Cell",
        mail: "Mail",
        close: "Close",
        savedSearches: "Saved searches",
        newestProducts: "Newest products from your searches",
        savedProducts: "Saved products",
        noSavedSearch:"No searches saved yet",
        noSavedProduct: "No new products for your searches yet",
        noSavedNewProduct:"No saved products yet",
        infoForSearchBox:"With the quick search you can search product names and<br/>product titles of our newly identified products. Thereafter<br />you can refine your search: For example,<br /> by limiting the results to certain product<br /> categories, countries or brands/manufacturers.",
        infoForSavedSearch: "Once you're done with configuring your search,<br/>you can save it. This helps in re-using<br /> the search and allows us to notify you<br /> via email when new products are available.",
        infoForSavedNewProduct: "Here you can constantly see the newest products<br/> that your searches identify.",
        infoForSavedProduct:"When you find a product that you'd like to<br/> within the results lists and get back to it here.",
        more: "More",
        startNewSearch: "Start new search",
        configureSearch: "Configure search",
        searchWordsInLocal: "Search words (in the local language)",
        andAllWords: "AND (all words)",
        orOneOfWords: "OR (one of the words)",
        updateResults: "Update results",
        saveSearchCreateAlert: "Save search & create alert",
        land: "Country",
        europe: "Europe",
        germany: "Germany",
        greatBritain: "Great Britain",
        france: "France",
        italy: "Italy",
        america: "America",
        usa: "USA",
        brazil: "Brazil",
        canada: "Canada",
        mexico: "Mexico",
        asiaPacific: "Asia-pacific",
        australia: "Australia",
        china: "China",
        india: "India",
        japan: "Japan",
        category: "Category",
        brandManufactureForTable: "Brand/<br>manufacturer",
        brandManufacture: "Brand manufacturer",
        availableSinceForTable: "Available<br>since",
        availableSince: "Available since",
        lastThirtyDays: "last 30 days",
        lastNinetyDays: "last 90 days",
        productTitle:"Product title",
        price: "Price",
        estimatedMonthlySales:"Estimated monthly sales",
        ratingNumber:"Rating (number)",
        ratingQuality: "Rating (quality)",
        searchResult: "Search results",
        search:"Search",
        anylize:"Analyze",
        forward:"Forward",
        download:"Download",
        saveForLater:"Save for later",
        noNewProducts:"No new products available with these search parameters.",
        moreThanThousand:"More than 1000 results",
        infoMoreThanThousand:"Your search has retrieved more than 1000 products, only the latest 1000 products are shown.",
        infoForSearchName:"The following name identifies the search within the list of saved searches:",
        inforForWeelyEmailing:"Weekly email alert containing newly available products:",
        errorEmptySearchName: "Bitte geben Sie der Suche einen Namen bevor Sie die Suche speichern",
        yes: "Yes",
        noAndOnlyNewProducts:"No (I want to go through the new products only within my browser)",
        save:"Save"
      },
      
    },
    de: {
      $vuetify: {
        dataIterator: {
          rowsPerPageText: 'Ergebnisse pro Seite',
          pageText: '{0}-{1} aus {2}',
        },
        dataTable:{
          itemsPerPageText: 'Ergebnisse pro Seite',
          
          ariaLabel: {
            sortNone: 'sort none',
            sortDescending: 'sort descending',
          },
        },
        dataFooter: {
          prevPage: 'prov',
          nextPage: 'next',
          itemsPerPageAll: 'items per page all'
        },
        noDataText: "no data text",

        logout: "Logout",
        help: "Hilfe",
        mainTitle:"Überwachen Sie automatisiert <br>den globalen Online-Handel.",
        emailAddress: "E-Mail-Adresse",
        password: "Passwort",
        login: "Anmelden",
        rememberMe: "Eingeloggt bleiben",
        passwordForgotten: "Probleme beim Einloggen?",
        emailPwdWrong: "Es tut uns leid. E-Mail oder Passwort ist falsch.",
        problemLogin: "Probleme beim Einloggen",
        requestSupport: "Dann senden Sie bitte eine E-Mail an hello@ecomda.de.<br> Wir werden uns schnellstmöglich bei Ihnen melden.",
        backLogin: "Zurück zum Login",
        feedbackWelcome: "Feedback welcome!",
        askAdditional: "Sie wünschen sich eine zusätzliche Funktion? Oder etwas funktioniert nicht, wie gedacht? Dann senden Sie uns gern eine Nachricht. Wir melden uns schnellstmöglich bei Ihnen!",
        name: "Name",
        message: "Nachricht",
        send: "Senden",
        thanksForFeedback: "Vielen Dank für Ihr Feedback!",
        askOtherIdeas: "Sie haben noch weitere Ideen oder Wünsche?",
        contactUsAnytime: "Dann können Sie uns auch gern<br>jederzeit direkt kontaktieren:",
        thomasJohn: "Thomas John",
        headOfProduct: "Head of Product",
        phone: "Phone",
        cell: "Cell",
        mail: "Mail",
        close: "Schließen",
        savedSearches: "Gespeicherte Suchen",
        newestProducts: "Neueste Produkte aus Ihren Suchen",
        savedProducts: "Gemerkte Produkte",
        noSavedSearch:"Bisher keine Suchen angelegt",
        noSavedProduct: "Bisher keine neuen Produkte zu Ihren Suchen",
        noSavedNewProduct:"Bisher keine Produkte auf die Merkliste gesetzt",
        infoForSearchBox:"Mit der Schnellsuche können Sie in Produktnamen und -titeln<br />neuer Produkte suchen. Im Anschluss können Sie die Suche<br />verfeinern: Beispielsweise durch Einschränkung auf bestimmte<br />Produktkategorien, Länder oder Hersteller/Marken.",
        infoForSavedSearch: "Wenn Sie eine Suche fertig konfiguriert haben,<br />können Sie die Suche speichern. Dadurch<br />können Sie die Suche immer wieder verwenden und sich<br />per E-Mail über neue Suchergebnisse benachrichtigen lassen.",
        infoForSavedNewProduct: "Hier sehen Sie regelmäßig die neuesten Produkte,<br />die Ihre gespeicherten Suchen liefern.",
        infoForSavedProduct:"Wenn Sie ein Produkt finden, das Sie sich später<br />noch einmal genauer anschauen möchten,<br />können Sie es auf die Merkliste setzen<br />und hier wiederfinden.",
        more: "Mehr",
        startNewSearch: "Neue Suche starten",
        configureSearch: "Suche anpassen",
        searchWordsInLocal: "Suchwörter (in Landessprache)",
        andAllWords: "Und (alle Wörter)",
        orOneOfWords: "Oder (eins der Wörter)",
        updateResults: "Ergebnisse aktualisieren",
        saveSearchCreateAlert: "Suche speichern & Alert einrichten",
        land: "Land",
        europe: "Europa",
        germany: "Deuschland",
        greatBritain: "Großbritannien",
        france: "Frankfreich",
        italy: "Italien",
        america: "America",
        usa: "USA",
        brazil: "Brasilien",
        canada: "Kanada",
        mexico: "Mexiko",
        asiaPacific: "Asien-Pazifik",
        australia: "Australien",
        china: "China",
        india: "Indien",
        japan: "Japan",
        category: "Kategorie",
        brandManufactureForTable: "Marke/<br>Hersteller",
        brandManufacture: "Marke Hersteller",
        availableSinceForTable: "Verfügbar<br>seit",
        availableSince: "Verfügbar seit",
        lastThirtyDays: "letzte 30 Tage",
        lastNinetyDays: "letzte 90 Tage",
        productTitle:"Produkttitel",
        price: "Preis",
        estimatedMonthlySales:"Geschätzte<br>Verkäufe<br>pro Monat",
        ratingNumber:"Rating (Anzahl)",
        ratingQuality: "Rating (Qualität)",
        searchResult: "Suchergebnisse",
        search:"Suchen",
        anylize:"Analysieren",
        forward:"Weiterleiten",
        download:"Download",
        saveForLater:"Zu Merkliste hinzufügen",
        noNewProducts:"Keine neuen Produkte für diese Suchparameter verfügbar.",
        moreThanThousand:"Mehr als 1000 Suchergebnisse",
        infoMoreThanThousand:"Ihre Suche hat mehr als 1000 Produkte geliefert, es werden nur die neuesten 1000 Produkte angezeigt.",
        infoForSearchName:"Der folgende Name identifiziert Ihre Suche in der Übersicht der gespeicherten Suchen:",
        inforForWeelyEmailing:"Wöchentliche E-Mail-Benachrichtigung über neu erscheinende Produkte:",
        errorEmptySearchName: "Bitte geben Sie der Suche einen Namen bevor Sie die Suche speichern",
        yes: "Ja",
        noAndOnlyNewProducts:"Nein (ich möchte neue Produkte mit meinem Browser anschauen)",
        save:"Speichern"
      },
      
    },
  }

  export default messages;