export const SET_PRODUCTS = 'SET_PRODUCTS';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const FINISH_PRODUCTS_REQUEST = 'FINISH_PRODUCTS_REQUEST';
export const SET_LOADINGPRODUCTS_ERROR = 'SET_LOADINGPRODUCTS_ERROR';
export const FAVOURITES_REQUEST = 'FAVOURITES_REQUEST';
export const SET_NUMBER_OF_PRODUCTS = 'SET_NUMBER_OF_PRODUCTS';